# Generated by Django 3.1.5 on 2021-01-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContourPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='point',
            constraint=models.CheckConstraint(check=models.Q(longitude__gte=-180), name='longitude_gte_minus_180'),
        ),
        migrations.AddConstraint(
            model_name='point',
            constraint=models.CheckConstraint(check=models.Q(longitude__lte=180), name='longitude_lte_180'),
        ),
        migrations.AddConstraint(
            model_name='point',
            constraint=models.CheckConstraint(check=models.Q(latitude__gte=-90), name='latitude_gte_minus_90'),
        ),
        migrations.AddConstraint(
            model_name='point',
            constraint=models.CheckConstraint(check=models.Q(latitude__lte=90), name='latitude_lte_90'),
        ),
        migrations.AddField(
            model_name='contourpoint',
            name='contour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinate', to='point.contour'),
        ),
        migrations.AddConstraint(
            model_name='contourpoint',
            constraint=models.CheckConstraint(check=models.Q(longitude__gte=-180), name='cp_longitude_gte_minus_180'),
        ),
        migrations.AddConstraint(
            model_name='contourpoint',
            constraint=models.CheckConstraint(check=models.Q(longitude__lte=180), name='cp_longitude_lte_180'),
        ),
        migrations.AddConstraint(
            model_name='contourpoint',
            constraint=models.CheckConstraint(check=models.Q(latitude__gte=-90), name='cp_latitude_gte_minus_90'),
        ),
        migrations.AddConstraint(
            model_name='contourpoint',
            constraint=models.CheckConstraint(check=models.Q(latitude__lte=90), name='cp_latitude_lte_90'),
        ),
    ]
