# Generated by Django 3.1.5 on 2021-01-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contourpoint',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
