# Generated by Django 3.1.5 on 2021-01-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_contourpoint_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contourpoint',
            name='contour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='point.contour'),
        ),
    ]
